version: '3.4'

services:
  online-ordering-api:
    image: online-ordering-chain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
