version: '3.4'

services:
  online-ordering-api:
    image: online-ordering-chain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', './dist/index.js']
